name: run-leap-year-tests
on:
  push:
    branch:
      - main
    pull_request:
      branches:
        - main

jobs:
  tests:
    name: "Run tests"
    runs_on: ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: actions/checkout@v3
      - name: Setup Python
        uses: action/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest -r w